export const exmapleProtein = [
  {
    pdbId: "1OKC",
    title: "Rhodopsin",
    organism: "Bos taurus",
    resolution: 2.8,
    depositionDate: "2002-10-15",
    authors: "Okada, T., Palczewski, K.",
    classification: "GPCR",
    chainCount: 1,
    ligandCount: 1,
  },
  {
    pdbId: "3RZE",
    title: "Adenosine A2A Receptor",
    organism: "Homo sapiens",
    resolution: 1.8,
    depositionDate: "2011-04-29",
    authors: "Liu, W., Chun, E., Jaakola, V.P.",
    classification: "GPCR",
    chainCount: 1,
    ligandCount: 2,
  },
  {
    pdbId: "6OIK",
    title: "Human CFTR",
    organism: "Homo sapiens",
    resolution: 3.2,
    depositionDate: "2019-04-10",
    authors: "Zhang, Z., Chen, J.",
    classification: "Channel",
    chainCount: 2,
    ligandCount: 4,
  },
  {
    pdbId: "5WUA",
    title: "GABAA Receptor",
    organism: "Homo sapiens",
    resolution: 3.9,
    depositionDate: "2017-05-22",
    authors: "Zhu, S., Noviello, C.M., Hibbs, R.E.",
    classification: "Channel",
    chainCount: 5,
    ligandCount: 3,
  },
  {
    pdbId: "6FN1",
    title: "ATP Synthase",
    organism: "Bos taurus",
    resolution: 3.4,
    depositionDate: "2018-01-18",
    authors: "Hahn, A., Vonck, J., Mills, D.J.",
    classification: "Complex",
    chainCount: 16,
    ligandCount: 8,
  },
];
